### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by GhostYiL** [Darkempire78/Raid-Protect-Discord-Bot#15]
Ikr Maybe im just dumb but mby someone would like to help :)
Bot starts without any erros, creates channels fine and roles.
But on user join im getting this error in console and no captcha appears the channel is just empty.

Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/runner/Raid-Protect-Discord-Bot/Cogs/onJoin.py", line 70, in on_member_join
    font = ImageFont.truetype(font= "arial", size= 60)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/PIL/ImageFont.py", line 852, in truetype
    return freetype(font)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/PIL/ImageFont.py", line 849, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/PIL/ImageFont.py", line 209, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by Darkempire78** [comment]
Do  use heroku, repl.it or similar option to run the bot ?

**Comment by GhostYiL** [comment]
Oh yeah i use repl.it

**Comment by Darkempire78** [comment]
It's a specific repl.it issue. 
Already answered here https://github.com/Darkempire78/Raid-Protect-Discord-Bot/issues/11

**Comment by GhostYiL** [comment]
Well from that topic he didn't resolved that issue on repl.it as i see

**Comment by Darkempire78** [comment]
Fixed with the last release!
