### ISSUE TITLE
Error while starting the bot

### ISSUE THREAD

**Issue by FeelsBadMan1** [Darkempire78/Raid-Protect-Discord-Bot#18]
Hello, i took a few cogs and added them to a globalbot that im creating however i get a fe error proably you could help.
```
D:\python\python.exe D:/my_python_projects/globalchat/main.py
D:\python\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.24.0 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
D:\python\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.24.0 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
D:\python\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator LinearSVC from version 0.24.0 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
D:\python\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator _SigmoidCalibration from version 0.24.0 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
D:\python\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator CalibratedClassifierCV from version 0.24.0 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
Traceback (most recent call last):
  File "D:\python\lib\site-packages\discord\ext\commands\bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\my_python_projects\globalchat\Cogs\onMessage.py", line 19, in <module>
    from Tools.logMessage import sendLogMessage
ModuleNotFoundError: No module named 'Tools.logMessage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/my_python_projects/globalchat/main.py", line 40, in <module>
    bot.load_extension(f"Cogs.{filename[:-3]}")
  File "D:\python\lib\site-packages\discord\ext\commands\bot.py", line 663, in load_extension
    self._load_from_module_spec(spec, name)
  File "D:\python\lib\site-packages\discord\ext\commands\bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.onMessage' raised an error: ModuleNotFoundError: No module named 'Tools.logMessage'

Process finished with exit code 1
```

**Comment by Darkempire78** [comment]
Do not forget to also add the Tools folder

**Comment by FeelsBadMan1** [comment]
Okey. however now it gives me this:

![image](https://user-images.githubusercontent.com/40109798/112262940-bc65a000-8c6e-11eb-9c6d-e03d11822ced.png)

**Comment by FeelsBadMan1** [comment]
```
D:\python\python.exe D:/my_python_projects/globalchat/main.py
Traceback (most recent call last):
  File "D:\python\lib\site-packages\discord\ext\commands\bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\my_python_projects\globalchat\Cogs\commands.py", line 84, in <module>
    async def joke(ctx):
TypeError: 'Cog' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/my_python_projects/globalchat/main.py", line 54, in <module>
    bot.load_extension(f"Cogs.{filename[:-3]}")
  File "D:\python\lib\site-packages\discord\ext\commands\bot.py", line 663, in load_extension
    self._load_from_module_spec(spec, name)
  File "D:\python\lib\site-packages\discord\ext\commands\bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.commands' raised an error: TypeError: 'Cog' object is not callable
```

**Comment by FeelsBadMan1** [comment]
Okey thanks but the antinude not detect imagres that are hentai as nudes

**Comment by FeelsBadMan1** [comment]
Well now the bot i starting usually but if it try to lead the cogs some of them fail to lead & others load like they should do

**Comment by Darkempire78** [comment]
> Okey thanks but the antinude not detect imagres that are hentai as nudes

Yes, all images are not detected as nudity, but it still works quite well

**Comment by FeelsBadMan1** [comment]
hmm... somehow the onMessage cog fails to load but all others are loading sucessfully but if i type a command it is not responsing like userinfo etc. i turned the helpcog to a cog where i will list all my commands in including the helpcommand but somehow its not working. probably a wrong indent but im not sure. would be nice if you know  how i may solve this.
![image](https://user-images.githubusercontent.com/40109798/112440925-2bb0c200-8d4b-11eb-9c00-cd65405dec9e.png)
![image](https://user-images.githubusercontent.com/40109798/112440981-39664780-8d4b-11eb-9240-2703ad25e51a.png)

**Comment by FeelsBadMan1** [comment]
> > Okey thanks but the antinude not detect imagres that are hentai as nudes
> 
> Yes, all images are not detected as nudity, but it still works quite well

i think its because it ignored admin. i will try it without adminprivelegs

**Comment by Darkempire78** [comment]
> > > Okey thanks but the antinude not detect imagres that are hentai as nudes
> > 
> > 
> > Yes, all images are not detected as nudity, but it still works quite well
> 
> i think its because it ignored admin. i will try it without adminprivelegs

That's right

**Comment by Darkempire78** [comment]
I removed the try/except in the new version when loading cogs so that it displays the error instead of "failed to load a cog".

**Comment by FeelsBadMan1** [comment]
okey. i tried to do a own helpcommand but now it tells me that the command "help" is not fund. However i clearly definied my helpcommand into the cog. here is the code form it probably you know why this happens:

https://pastebin.com/VjTxz0f2

**Comment by Darkempire78** [comment]
It's not really an error with Raid Protect ...
